### ISSUE TITLE
[bug] dynpaper --init

### ISSUE THREAD

**Issue by nyghtly-derek** [oddProton/dynpaper#18]
I got this error when running the `dynpaper --init` command.

````
Traceback (most recent call last):
  File "/home/nyghtly/.local/bin/dynpaper", line 11, in <module>
    sys.exit(main())
  File "/home/nyghtly/.local/lib/python3.6/site-packages/dynpaper/__init__.py", line 5, in main
    dpmain(argv)
  File "/home/nyghtly/.local/lib/python3.6/site-packages/dynpaper/dynpaper.py", line 97, in main
    args = arguments(argv)
  File "/home/nyghtly/.local/lib/python3.6/site-packages/dynpaper/arguments.py", line 49, in arguments
    args = load_args(args)
  File "/home/nyghtly/.local/lib/python3.6/site-packages/dynpaper/arguments.py", line 26, in load_args
    yaml.dump(DEFAULT_CONFIG, fp, default_flow_style=False)
NameError: name 'DEFAULT_CONFIG' is not defined
````

**Comment by oddProton** [comment]
Ah, i thought I had it corrected.   
Update with:  
```sh 
pip install --user --upgrade --no-cache dynpaper
 ```

**Comment by nyghtly-derek** [comment]
It worked! Thanks.

**Comment by oddProton** [comment]
Sweet, thanks for taking time to open an issue! Have fun!
