### ISSUE TITLE
AttributeError: 'Period' object has no attribute 'is_future'

### ISSUE THREAD

**Issue by icex** [oddProton/dynpaper#19]
Hi 
I got this error when trying to run it with your example(small just a change in the wallpapers path)

  File "/home/bogdan/.local/bin/dynpaper", line 11, in <module>
    sys.exit(main())
  File "/home/bogdan/.local/lib/python3.6/site-packages/dynpaper/__init__.py", line 5, in main
    dpmain(argv)
  File "/home/bogdan/.local/lib/python3.6/site-packages/dynpaper/dynpaper.py", line 99, in main
    wallpaper, target = sync_wallpapers()
  File "/home/bogdan/.local/lib/python3.6/site-packages/dynpaper/dynpaper.py", line 74, in sync
    while (wallpapers[-1][1] - interval).is_future():
AttributeError: 'Period' object has no attribute 'is_future'

System:
Ubuntu 18.04
Python 3.6.5

**Comment by oddProton** [comment]
What's the output of `pip list`?

**Comment by icex** [comment]
```
Package                 Version  
----------------------- ---------
apturl                  0.5.2    
asn1crypto              0.24.0   
Brlapi                  0.6.6    
certifi                 2018.1.18
chardet                 3.0.4    
chrome-gnome-shell      0.0.0    
colorful                0.4.1    
command-not-found       0.3      
cryptography            2.1.4    
cupshelpers             1.0      
defer                   1.0.6    
distro-info             0.18     
dynpaper                2.0.5    
evdev                   0.7.0    
httplib2                0.9.2    
idna                    2.6      
keyring                 10.6.0   
keyrings.alt            3.0      
language-selector       0.1      
launchpadlib            1.10.6   
lazr.restfulclient      0.13.5   
lazr.uri                1.0.3    
louis                   3.5.0    
macaroonbakery          1.1.3    
Mako                    1.0.7    
MarkupSafe              1.0      
oauth                   1.0.1    
olefile                 0.45.1   
pbr                     4.2.0    
pendulum                2.0.2    
pexpect                 4.2.1    
Pillow                  5.1.0    
pip                     18.0     
prettyprinter           0.14.0   
protobuf                3.0.0    
py-buzz                 0.3.4    
pycairo                 1.16.2   
pycrypto                2.6.1    
pycups                  1.9.73   
Pygments                2.2.0    
pygobject               3.26.1   
pymacaroons             0.13.0   
PyNaCl                  1.1.2    
pyRFC3339               1.0      
python-apt              1.6.2    
python-dateutil         2.7.3    
python-debian           0.1.32   
pytz                    2018.3   
pytzdata                2018.5   
pyudev                  0.21.0   
pyxdg                   0.25     
PyYAML                  3.13     
reportlab               3.4.0    
requests                2.18.4   
requests-unixsocket     0.1.5    
schema                  0.6.8    
screen-resolution-extra 0.0.0    
SecretStorage           2.3.1    
setuptools              40.0.0   
simplejson              3.13.2   
six                     1.11.0   
system-service          0.3      
systemd-python          234      
tendo                   0.2.12   
ubuntu-drivers-common   0.0.0    
ufw                     0.35     
unattended-upgrades     0.1      
urllib3                 1.22     
usb-creator             0.3.3    
wadllib                 1.3.2    
wheel                   0.30.0   
xkit                    0.0.0    
zope.interface          4.3.2    

```

**Comment by oddProton** [comment]
Did you get this error right after
`dynpaper -f <path>`
?

**Comment by icex** [comment]
Yes,

~$ dynpaper -f Pictures/Wallpapers/mojave/config.yml 
Traceback (most recent call last):
  File "/home/bogdan/.local/bin/dynpaper", line 11, in <module>
    sys.exit(main())
  File "/home/bogdan/.local/lib/python3.6/site-packages/dynpaper/__init__.py", line 5, in main
    dpmain(argv)
  File "/home/bogdan/.local/lib/python3.6/site-packages/dynpaper/dynpaper.py", line 99, in main
    wallpaper, target = sync_wallpapers()
  File "/home/bogdan/.local/lib/python3.6/site-packages/dynpaper/dynpaper.py", line 74, in sync
    while (wallpapers[-1][1] - interval).is_future():
AttributeError: 'Period' object has no attribute 'is_future'

**Comment by oddProton** [comment]
It should be fixed now.  
`pip3 install --upgrade dynpaper --no-cache --user`

**Comment by icex** [comment]
Looks nice :) thanks for the help

**Comment by oddProton** [comment]
NP. thanks for writing an issue!
